import { Inter } from "next/font/google";
import Head from "next/head";

import styles from "@/styles/Home.module.css";

import Access from "./components/access";
import Contact from "./components/contact";
import Footer from "./components/footer";
import Header from "./components/header";
import Hero from "./components/hero";
import Lead from "./components/lead";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Hero />
        <div className={styles.content_wrapper}>
          <Lead />
          <Access />
          <Contact />
        </div>
      </main>
      <Footer />
    </>
  );
}
